name: MyChunks
main: net.betterverse.mychunks.MyChunks
version: 0.1.1
author: Spudstabber
description: Simple chunk-based protection
startup: postworld
depend: [Vault]
commands:
  mychunks:
    description: Used to own the current Chunk that you are in
    usage: /<command> help
permissions:
  mychunks.own:
    default: true
    description: Needed to manage owned Chunks (/chunk buy, /chunk sell, /chunk list, /chunk clear)
  mychunks.info:
    default: true
    description: Needed to see who the owner and CoOwners are of the current Chunk (/chunk info)
  mychunks.coowner:
    default: true
    description: Needed to add a CoOwner to your Chunk (/chunk coowner)
  mychunks.free:
    default: op
    description: Own Chunks free of charge
  mychunks.admin:
    default: op
    description: Edit other Players' Chunks
  mychunks.mustowntobuild:
    default: false
    description: Restricts Players from building anywhere they don't own that is above the OwnLowerLimit level
  mychunks.limit.-1:
    default: true
    description: limit the number of Chunks a player can own. -1 = unlimited. -1 can be changed to any number 0 - 100. Largest number is taken if player has more than 1 node (-1 is considered larger than 100)
  mychunks.limit.0:
    default: true
    description: limit the number of Chunks a player can own. -1 = unlimited. -1 can be changed to any number 0 - 100. Largest number is taken if player has more than 1 node (-1 is considered larger than 100)
  mychunks.limit.1:
    default: true
    description: limit the number of Chunks a player can own. -1 = unlimited. -1 can be changed to any number 0 - 100. Largest number is taken if player has more than 1 node (-1 is considered larger than 100)
  mychunks.limit.2:
    default: true
    description: limit the number of Chunks a player can own. -1 = unlimited. -1 can be changed to any number 0 - 100. Largest number is taken if player has more than 1 node (-1 is considered larger than 100)
  mychunks.limit.3:
    default: true
    description: limit the number of Chunks a player can own. -1 = unlimited. -1 can be changed to any number 0 - 100. Largest number is taken if player has more than 1 node (-1 is considered larger than 100)
  mychunks.limit.4:
    default: true
    description: limit the number of Chunks a player can own. -1 = unlimited. -1 can be changed to any number 0 - 100. Largest number is taken if player has more than 1 node (-1 is considered larger than 100)
  mychunks.limit.5:
    default: true
    description: limit the number of Chunks a player can own. -1 = unlimited. -1 can be changed to any number 0 - 100. Largest number is taken if player has more than 1 node (-1 is considered larger than 100)
  mychunks.limit.10:
    default: true
    description: limit the number of Chunks a player can own. -1 = unlimited. -1 can be changed to any number 0 - 100. Largest number is taken if player has more than 1 node (-1 is considered larger than 100)
  mychunks.limit.20:
    default: true
    description: limit the number of Chunks a player can own. -1 = unlimited. -1 can be changed to any number 0 - 100. Largest number is taken if player has more than 1 node (-1 is considered larger than 100)
  mychunks.limit.50:
    default: true
    description: limit the number of Chunks a player can own. -1 = unlimited. -1 can be changed to any number 0 - 100. Largest number is taken if player has more than 1 node (-1 is considered larger than 100)
  mychunks.limit.100:
    default: true
    description: limit the number of Chunks a player can own. -1 = unlimited. -1 can be changed to any number 0 - 100. Largest number is taken if player has more than 1 node (-1 is considered larger than 100)